/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/goals` | `/goals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/production-dashboard` | `/production-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/productions` | `/productions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/goals` | `/goals`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/production-dashboard` | `/production-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/productions` | `/productions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/login${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/goals${`?${string}` | `#${string}` | ''}` | `/goals${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/production-dashboard${`?${string}` | `#${string}` | ''}` | `/production-dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/productions${`?${string}` | `#${string}` | ''}` | `/productions${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/products${`?${string}` | `#${string}` | ''}` | `/products${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/sales${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/stock${`?${string}` | `#${string}` | ''}` | `/stock${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/goals` | `/goals`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/production-dashboard` | `/production-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/productions` | `/productions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/products` | `/products`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/sales` | `/sales`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/stock` | `/stock`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
